### ISSUE TITLE
最新的版本的 样式路径引入问题

### ISSUE THREAD

**Issue by zhaoyunchong** [heikaimu/vue3-waterfall-plugin#10]
![1666317555809](https://user-images.githubusercontent.com/52824245/197093385-8714f28c-e869-405b-91d7-c19855d12b94.jpg)

我按照文档上的样式引入 不行。更改下路径才可以
```javascript
import 'vue-waterfall-plugin-next/dist/style.css'
```
 
最后感谢 作者提供插件。

**Comment by heikaimu** [comment]
是的，很奇怪的问题，有的版本需要加dist，有的又不需要加，谢谢支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue3-waterfall-plugin] 最新的版本的 样式路径引入问题 (Issue #10)





 

 
我按照文档上的样式引入 不行。更改下路径才可以
 import 'vue-waterfall-plugin-next/dist/style.css'  
最后感谢 作者提供插件。

**Comment by IITII** [comment]
原因是这个导出到处改,,,,,,, @heikaimu @zhaoyunchong 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/33705067/224024054-d1c4f58f-e82c-46d5-8b0d-bc188963eef7.png">
