### ISSUE TITLE
图片 CORS 问题

### ISSUE THREAD

**Issue by IITII** [heikaimu/vue3-waterfall-plugin#13]
## 疑问

`image.crossOrigin = 'Anonymous'` 真的有必要吗？加了反而不能正常显示了

手动修改本地 my-lib.es.js, 去除 `image.crossOrigin = 'Anonymous'` 可以正常显示

https://github.com/heikaimu/vue3-waterfall-plugin/blob/cdb8ceb22eef75c29d0f7db111581f4cdf5e2c24/lib/utils/loader.ts#L20

## 问题截图

![image](https://user-images.githubusercontent.com/33705067/216757647-de1dc296-382c-4e5e-8e96-21ccdf204697.png)

## 环境

nodejs 16.x.x
"vue-waterfall-plugin-next": "^2.1.11",

后端是 moleculer 起的 api 和 file server，允许跨域，跨域api可以正常调用

## 网上讨论
https://segmentfault.com/q/1010000008648867

**Comment by xjpe** [comment]
同样问题，解决了吗

**Comment by IITII** [comment]
很早之前发了 PR, 作者没 merge

xjpe ***@***.***> 于2023年4月10日周一 10:22写道：

**Comment by heikaimu** [comment]
那个有点儿粗暴了，一般情况下，你的图片存储服务器都应该是会添加CORS的，我把跨域改成参数吧，默认开启

**Comment by heikaimu** [comment]
v2.2.1已添加跨域参数

**Comment by xjpe** [comment]
直接nginx又做了层代理。。

**Comment by IITII** [comment]
实际上 我试过 下面两种方式, 都运行跨域访问, 但是因为这个 `image.crossOrigin = 'Anonymous'` 被浏览器拒绝了.

* 后端是 moleculer 起的 api 和 file server，允许跨域，跨域api可以正常调用
* python http.server


而且 OOS 一般开的是 header 验证吧, 验证下 Refer... @heikaimu
