### ISSUE TITLE
div容器中的动画属性如何去掉

### ISSUE THREAD

**Issue by lijianxiong** [heikaimu/vue3-waterfall-plugin#17]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4301287/232247643-34337602-7d11-46d5-b0e9-12db9ab1f9bb.png">
不想要这个动画属性怎么去掉

**Comment by heikaimu** [comment]
animationDelay，animationDuration 这两个参数都设置为0

**Comment by lijianxiong** [comment]
> animationDelay，animationDuration 这两个参数都设置为0

太感动了回复我了.

**Comment by heikaimu** [comment]
难得看一下git，见谅 :(
