### ISSUE TITLE
当在keep-alive中使用时，切换router后console抛异常

### ISSUE THREAD

**Issue by amonyaos** [heikaimu/vue3-waterfall-plugin#18]
my-lib.es.js 小问题，不影响使用，但是抛异常引起开发者困惑

<img width="561" alt="image" src="https://user-images.githubusercontent.com/12334944/232260714-c40eda70-3dd2-4908-8ada-aa0c3957081f.png">

观察到 wrapperWidth.value 为 0，colWidth.value 为 0，执行 renderer 后执行 layoutHandle 中的 initY
```
watch(() => [wrapperWidth, colWidth, props.list], () => {
      renderer();
    }, { deep: true });
```
此时 cols.value 为 NaN，new Array(cols.value) 抛异常
```
const initY = () => {
    posY.value = new Array(cols.value).fill(props.hasAroundGutter ? props.gutter : 0);
  };
```
源码位置：[lib/use/useLayout.ts](https://github.com/heikaimu/vue3-waterfall-plugin/blob/master/lib/use/useLayout.ts#L31)

**Comment by heikaimu** [comment]
已经修复
