### ISSUE TITLE
遇到一个问题，前几个布局还是正常的，后面的会被覆盖。

### ISSUE THREAD

**Issue by sindaZeng** [heikaimu/vue3-waterfall-plugin#21]
这是正常的前几个
![正常](https://github.com/heikaimu/vue3-waterfall-plugin/assets/40020637/51c31748-04f2-4c14-8f5a-a9cd70aeba1e)

这是后面的布局计算错误的
![不正常](https://github.com/heikaimu/vue3-waterfall-plugin/assets/40020637/826ec4e5-2a2e-4308-a9b0-6a8e6429ed62)

**Comment by sindaZeng** [comment]
我发现只要改变一下窗口大小即可重新排列，重新排列后就正确的。。。

**Comment by heikaimu** [comment]
你可以试试把`delay `这个参数的值修改下

**Comment by sindaZeng** [comment]
> 你可以试试把`delay `这个参数的值修改下

我试了无效。具体查了原因，我的图片使用了懒加载，没有加载出来的时候固定了一张未加载的图片。最后懒加载中加载完成回调统计数量，然后重新排列。还是感谢大佬的代码。

**Comment by heikaimu** [comment]
你自己不用懒加载啊，我插件有懒加载的功能啊

**Comment by WindSing-zhang** [comment]
用楼主提供的LazyImg标签就行了
