### ISSUE TITLE
首次获取的未缓存的图片，导致布局重叠，要重新触发刷新布局才正常

### ISSUE THREAD

**Issue by MuYo1218** [heikaimu/vue3-waterfall-plugin#30]

**Comment by MuYo1218** [comment]
![image](https://github.com/heikaimu/vue3-waterfall-plugin/assets/92902130/20c2acf0-be6f-45a1-b329-b3304db75086)
我这没法使用作者的LazyImg组件，因为使用了另一个预览图片的组件，展示预览图，需要往img标签身上写自定义属性绑定原图的地址

**Comment by heikaimu** [comment]
代码更新了下，提供了一个renderer的方法，你可以看下，在你懒加载完成后去强制出发重绘。这也是LazyImg里面做了的事情，只是你现在需要自己做一下
