### ISSUE TITLE
用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16

### ISSUE THREAD

**Issue by blackomilk** [heikaimu/vue3-waterfall-plugin#32]
用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16，有碰到这情况的吗

**Comment by heikaimu** [comment]
crossOrigin = false, 我记得几天才有人问了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月31日(星期四) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue3-waterfall-plugin] 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16 (Issue #32)





 
用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16，有碰到这情况的吗

**Comment by blackomilk** [comment]
> crossOrigin = false, 我记得几天才有人问了的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月31日(星期四) 下午3:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [heikaimu/vue3-waterfall-plugin] 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16 (Issue #32) 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16，有碰到这情况的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

> crossOrigin = false, 我记得几天才有人问了的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月31日(星期四) 下午3:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [heikaimu/vue3-waterfall-plugin] 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16 (Issue #32) 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16，有碰到这情况的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

加了这个了，也不行

**Comment by blackomilk** [comment]
:list="demoList"
      :gutter="0"
      :width="width"
      class="works_list"
      :breakpoints="{ 1400: { rowPerView: num } }"
      :crossOrigin="false"
      ref="masonry"

**Comment by blackomilk** [comment]
> crossOrigin = false, 我记得几天才有人问了的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月31日(星期四) 下午3:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [heikaimu/vue3-waterfall-plugin] 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16 (Issue #32) 用waterfall组件包起来的图片就报CORS，直接用img标签就可以正常显示，node 16，有碰到这情况的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
