### ISSUE TITLE
添加搜索功能

### ISSUE THREAD

**Issue by didiplus** [heikaimu/vue3-waterfall-plugin#34]
第一次请求没有问题，再次加载就出现问题
搜索组件传递参数，后调用父组件的handleLoadMore

子组件

`<script setup lang="ts">
import {  ref ,defineEmits} from 'vue'
const emits = defineEmits(['childEvent'])
const keywork = ref("")
const handleEnter = () =>{
    emits('childEvent',keywork.value)
}
</script>
`
父组件
`
onMounted(() => {
  handleLoadMore("风景")
})

// 加载更多
function handleLoadMore(keywork:string) {

  toutiao_search_pic({
    page: page.value,
    size: props.pageSize,
    term: keywork
  }).then((res) => {
    list.value.push(...res)
    page.value += props.pageSize
  })
}
`
请教一下，要实现这个功能如何做

**Comment by heikaimu** [comment]
我的example里面就是加载更多，你可以看看里面的代码
