### ISSUE TITLE
list改变重绘是强制的吗，我这边现在第一页list数据加载回来就会重绘一下，然后图片就会跳一下，怎么才能不跳呢，直接显示在相应位置

### ISSUE THREAD

**Issue by blackomilk** [heikaimu/vue3-waterfall-plugin#36]
list改变重绘是强制的吗，我这边现在第一页list数据加载回来，有的这种空白区域就会重绘一下，然后图片就会跳一下，怎么才能不跳呢，直接显示在相应位置
<img width="1418" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/42260316/f2f75d87-d4da-4c37-a223-ea7b15f57621">

**Comment by heikaimu** [comment]
图片的高度，除非你一开始就知道，否则都只能等到图片渲染完成之后再去重新计算高度，所以，除非你知道这个图片的宽高，然后给图片的外容器写这个比例的div容器块。这样就不会跳动了，别无他法了。

**Comment by blackomilk** [comment]
可以了，多谢。图片报跨域的问题还有解吗，别人电脑windows可以就我的不行。。。。我的是mac

**Comment by heikaimu** [comment]
跨域那个确实不知道你的情况了，你可以看下你数据源的问题，比如是否图片存储服务器开了跨域的，然后就需要把插件的跨域打开。

**Comment by blackomilk** [comment]
应该不是图片问题，别人的windows电脑能打开，就我的mac不能。。而且不用瀑布流我这能打开，不知道卡在哪了

**Comment by heikaimu** [comment]
你这问题太含糊了，我也没法回答你啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月14日(星期四) 中午12:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heikaimu/vue3-waterfall-plugin] list改变重绘是强制的吗，我这边现在第一页list数据加载回来就会重绘一下，然后图片就会跳一下，怎么才能不跳呢，直接显示在相应位置 (Issue #36)





 
应该不是图片问题，别人的windows电脑能打开，就我的mac不能。。而且不用瀑布流我这能打开，不知道卡在哪了

**Comment by blackomilk** [comment]
我本地nginx代理处理了一下，现在有个新问题。。。开始路由缓存的页面每次进入图片都会叠在第一张，然后展开，这个有办法处理吗
