### ISSUE TITLE
大佬，已经排列好的，怎么重新刷新数据？

### ISSUE THREAD

**Issue by LindaPhillips820191** [heikaimu/vue3-waterfall-plugin#37]
比如我选了分类A，加载了30条数据，并且都排列显示好了。这个时候我选分类B，又加载了30条数据，我把Waterfall 的list值重新刷新，没有效果，调用 waterfall.value.renderer() 也不行

**Comment by heikaimu** [comment]
waterfall.value.renderer() 你确定调用到了的吗

**Comment by LindaPhillips820191** [comment]
> waterfall.value.renderer() 你确定调用到了的吗

感谢回复，起先已经解决拉，是delay的问题。还有有个问题想请教下，我打开图片预览，这个时候滚动条会丢失，关闭预览，滚动条又出来了。导致的页面抖动问题，有什么避免方法吗

**Comment by heikaimu** [comment]
如果你想完全避免这种情况，你的外容器需要用滚动插件，就是那种滚动条其实是定位在页面上的，不会占用宽度的。或者还有个办法，你在点击预览的时候，给你页面添加一个右border, 宽度和你的滚动条宽度一样，然后关闭预览的时候去掉这个border :)

**Comment by Salvatore-zl** [comment]
> > waterfall.value.renderer() 你确定调用到了的吗
> 
> 感谢回复，起先已经解决拉，是delay的问题。还有有个问题想请教下，我打开图片预览，这个时候滚动条会丢失，关闭预览，滚动条又出来了。导致的页面抖动问题，有什么避免方法吗

delay的什么问题啊？   选了分类A，加载了30条数据，并且都排列显示好了。这个时候我选分类B，又加载了30条数据，我把Waterfall 的list值重新刷新，没有效果 数据确定变啦  但是图片没有刷新
