### ISSUE TITLE
是否考虑暴露图片加载失败时候的 Event

### ISSUE THREAD

**Issue by IITII** [heikaimu/vue3-waterfall-plugin#39]
* 目前图片加载失败只会在 Console 里面输出一行日志, 不是很直观
* 如果暴露了图片加载失败的 Event, 可以自己定义加载后的操作, 比如提示加载失败. 体验上会好很多
<img width="1064" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/33705067/7f13a9a9-f4e0-45e6-8555-2405db0a123b">

**Comment by heikaimu** [comment]
已经更新，添加了懒加载组件的`success`，`error`事件 :)
