### ISSUE TITLE
高度不变化

### ISSUE THREAD

**Issue by NJHSFNAK** [heikaimu/vue3-waterfall-plugin#41]
调用waterfallRef.value.renderer()后，发现高度不发生变化
<img width="1726" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/38530519/396c96bf-0e60-4d8f-8fc5-112eb13303dc">

**Comment by NJHSFNAK** [comment]
我发现waterfallRef.value返回的值中有一个属性是wrapperHeight，是直接可以通过这个属性来进行修改高度吗？

**Comment by heikaimu** [comment]
我看你第一张图的waterfall-list标签内没有任何东西啊？那高度肯定是0啊

**Comment by NJHSFNAK** [comment]
不是哦，你看高度是2329.58px

**Comment by NJHSFNAK** [comment]
> 我看你第一张图的waterfall-list标签内没有任何东西啊？那高度肯定是0啊
不是哦，你看高度是2329.58px

**Comment by heikaimu** [comment]
我也测试了一下数组为0的情况，计算出来的高度也是0，没有出现你的情况，你可以看下是不是你外层容器定位的问题，或则提供更详细的情景。

**Comment by NJHSFNAK** [comment]
> 我也测试了一下数组为0的情况，计算出来的高度也是0，没有出现你的情况，你可以看下是不是你外层容器定位的问题，或则提供更详细的情景。

<img width="1727" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/38530519/a248f43b-422a-4090-a69c-6d32ce1df31e">
是不是因为我外面的div设置了最大高度的原因？因为我想的是在一个div中滚动，不太想页面滚动

**Comment by Chauban** [comment]
> > 我也测试了一下数组为0的情况，计算出来的高度也是0，没有出现你的情况，你可以看下是不是你外层容器定位的问题，或则提供更详细的情景。
> 
> <img alt="image" width="1727" src="https://user-images.githubusercontent.com/38530519/277295912-a248f43b-422a-4090-a69c-6d32ce1df31e.png"> 是不是因为我外面的div设置了最大高度的原因？因为我想的是在一个div中滚动，不太想页面滚动

请问div滚动实现了吗？我也想用div滚动，但是结合tailwindcss做不出来

**Comment by heikaimu** [comment]
你们可以看下我例子里面那个弹窗，就是点击外面卡片出来的弹窗，那就是一个div滚动啊。代码就在example里面。

**Comment by heikaimu** [comment]
你可以把你外容器高度写一个固定的px试试，比如500px这种，还有不知道是不是你那个aside影响到的，你可以先不放里面试试。
