### ISSUE TITLE
README.md没有写明breakpoints优先级高于width, 以及没有写breakpoints的默认值

### ISSUE THREAD

**Issue by Firkraag** [heikaimu/vue3-waterfall-plugin#42]
使用width指定卡片的宽度一直不成功, 看了几个小时源码才知道breakpoints有未写在文档中的默认值:

>  breakpoints: {
      type: Object,
      default: () => ({
        1200: {
          rowPerView: 3
        },
        800: {
          rowPerView: 2
        },
        500: {
          rowPerView: 1
        }
      })
    },

并且breakpoints优先级高于width, 只是使用width指定卡片的宽度是无法生效的

**Comment by heikaimu** [comment]
不好意思我的问题，文档里面写的和默认的没有对应上。已修改，谢谢提醒。

**Comment by Firkraag** [comment]
<img width="843" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/4558542/3cee9ca4-8e01-4dde-9818-8b0d114bc451">
这里breakpoints的默认值不明确, 最好也改一下.  以我作为用户的经验, 看到这里breakpoints和width能够设置每行卡片个数就不会再往下看了.

我提交了一个pull request #43
