### ISSUE TITLE
使用组件加载图片跨域，直接img引入却是正常的

### ISSUE THREAD

**Issue by qingchen1998** [heikaimu/vue3-waterfall-plugin#5]
用组件的情况下，图片发生跨域，但是，我直接用<img src="" />引入却是没问题的，请问是怎么回事？请教一下
**下面是直接引入**
![waterfall-直接引入.png](https://tucang.cc/api/image/show/d508cc173b507966e4c029d9ae60c856)
![waterfall-直接引入请求.png](https://tucang.cc/api/image/show/bd09c8bc4b83a7eb2d317e8a58a5d168)
**下面是使用组件**
![waterfall-组件引入.png](https://tucang.cc/api/image/show/8e86f9f6bfff39c4377432c537a8d7ee)
![waterfall-组件引入请求.png](https://tucang.cc/api/image/show/36be2f193fa48a01caaee70f407eb3a8)

**Comment by qingchen1998** [comment]
图片地址：https://dingyue.ws.126.net/2022/0526/e810d6a6j00rcg7ca000td0007i00b8p.jpg

**Comment by heikaimu** [comment]
首先你图片和你现在的项目服务器是存在跨域关系的。而dom里面的img标签本身是不会有跨域的。但是js里面的img是带了cross origin的。插件里会有js去加载图片。所以要解决这个问题。要么就像我例子里面用第三方前缀临时解决。要么就把你们图片资源的跨域设置了。

**Comment by qingchen1998** [comment]
谢谢

**Comment by qingchen1998** [comment]
//image.crossOrigin = 'Anonymous' // 支持跨域图片

把这行代码注释掉   就ok了

**Comment by heikaimu** [comment]
嗯，后面有时间了我提个PR把crossOrigin设置成参数传递就好了

**Comment by lilulu806** [comment]
我也遇到了同样的问题，并且后端返回的图片地址还要加上前缀，怎么解决啊

**Comment by heikaimu** [comment]
crossOrigin = false

**Comment by lilulu806** [comment]
啊啊解决了，非常感谢
