### ISSUE TITLE
允许卡片左对齐

### ISSUE THREAD

**Issue by horans** [heikaimu/vue3-waterfall-plugin#51]
目前卡片的默认排布为居中对齐无法修改，希望能开放左对齐（以及右对齐）的设置，这在有侧边栏的布局下更为友好。

> TITLE: Allow cards to align to the left.
> DESC: Currently the default layout of cards is fixed "align to center". It would be great to add an option to change to "align to left" (or right). This will be more friendly to layouts with sidebars.

**Comment by heikaimu** [comment]
最新版本`2.2.10`已经添加了`align`属性，允许值`left | center | right`,默认'center'.
