### ISSUE TITLE
是否有render 成功后的方法？

### ISSUE THREAD

**Issue by ccc961125** [heikaimu/vue3-waterfall-plugin#56]
delay使用的默认 300 因为计算布局，会导致有空白等待的时间

**Comment by heikaimu** [comment]
你说的等待白屏时间是什么时候产生的？

**Comment by heikaimu** [comment]
获取到数据的时候马上就会就行一次计算渲染，这个过程中如果有图片渲染完成了，会重新计算渲染。这里的delay是用于陆续有图片渲染完成的时候，只会在最后进行一次渲染。所以我不明白你说的白屏是在什么时候。

**Comment by ccc961125** [comment]
接口加载完成后 但数据并没有渲染出来（列表中没有图片）看起来有一个等待

**Comment by ccc961125** [comment]
https://github.com/heikaimu/vue3-waterfall-plugin/assets/161785998/ccdcdd1a-e53f-428e-87a5-ff9d6fef24e7

**Comment by heikaimu** [comment]
你这个中途弹了一个“没有更多了”，然后才是出来插件列表。我感觉是你的loading之后并没有第一时间拿到列表数据。正常情况应该是loading之后有一小段白屏（正常的插件渲染时间），然后再显示列表。

**Comment by ccc961125** [comment]
没有更多了～和列表为同级，一小段白屏的就是计算布局的时间吧，所以是不是应该 抛出一个render 成功后的方法

**Comment by heikaimu** [comment]
你现在是想在这个方法里做什么事情呢？

**Comment by ccc961125** [comment]
render 完成后再去把pageloading 移除掉

**Comment by heikaimu** [comment]
你的需求是不是，loading消失的时候，这个列表就完成的展示出来咯？中间没有任何过渡

**Comment by ccc961125** [comment]
对

**Comment by ccc961125** [comment]
这个方法目前要加吗

**Comment by heikaimu** [comment]
你更新下2.4.2版本，加了一个 `afterRender`，方法，具体看下文档。在线列子里面也用这个实现了一个loading

**Comment by ccc961125** [comment]
好的感谢

**Comment by ccc961125** [comment]
发包了吗没下载下来呢

**Comment by heikaimu** [comment]
发了，你用npm原镜像下载，淘宝镜像应该还没有同步。
https://www.npmjs.com/package/vue-waterfall-plugin-next

**Comment by ccc961125** [comment]
这个大概多久同步啊，原镜像下载不下来呢

**Comment by heikaimu** [comment]
npm i vue-waterfall-plugin-next@2.4.3 
你试试这个，我这边测试可以。
