### ISSUE TITLE
关于懒加载图片适配问题

### ISSUE THREAD

**Issue by blackomilk** [heikaimu/vue3-waterfall-plugin#57]
<img width="1183" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/42260316/ef8e7915-5cb3-4e30-b32c-5b808e5ae48b">
业务逻辑是，每张图片模块有个模糊底层背景，然后在上边又加了一层懒加载图片，做出类似卡片的效果，但是底层的懒加载图片就可以100%占满父元素，上层的图片父元素是绝对定位，为啥上层的懒加载图片就占不满父元素呢，宽高比跟底层父元素宽高比是一致呢呀，求大神来给看看。
  上层图片父元素绝对定位代码      
         position: absolute;
          top: 20rem;
          right: 20rem;
          bottom: 20rem;
          left: 20rem;

**Comment by heikaimu** [comment]
懒加载组件用的哪个？

**Comment by blackomilk** [comment]
<template #item="{ item }">
            <div class="item" @click="toPicDetail(item)" v-if="item.img_url">
              <div
                class="works"
                v-if="item.size.showHeight"
                :style="{
                  height:
                    !resizeView && isPc == 1
                      ? item.size.showHeight + 'Px'
                      : 'auto',
                }"
              >
                <LazyImg
                  :url="url + item.img_url"
                  v-on:contextmenu="preventContextMenu"
                  ref="lazyImg"
                  @success="lazyImgLoadSuccess1"
                />
                <div class="works-mask" v-if="item.lazyImgLoad1"></div>
                <div class="w-toast">
                  <div class="toast-mask"></div>
                  <LazyImg
                    :url="url + item.img_url"
                    v-on:contextmenu="preventContextMenu"
                    ref="lazyImg"
                    @success="lazyImgLoadSuccess"
                  />
                  <div class="w-t-btns" v-if="item.lazyImgLoad">
                    <div><img src="./images/btn1.png" alt="" /></div>
                    <div><img src="./images/btn2.png" alt="" /></div>
                    <div><img src="./images/btn3.png" alt="" /></div>
                    <div><img src="./images/btn4.png" alt="" /></div>
                  </div>
                </div>
                <div class="user-info" v-if="item.user.url && item.lazyImgLoad">
                  
                  <div class="info">
                    <div class="avatar">
                      <img :src="url + item.user.url" alt="" />
                    </div>
                    <div class="name">
                      <span>{{ item.user.username }}</span>
                      <img :src="url + item.user.medal.img_url" alt="" />
                    </div>
                  </div>
                  <div class="xin">
                    <div
                      v-if="item.like_status"
                      @click.stop="starClick(0, item)"
                    >
                      <img src="./images/xin_select.png" alt="" />
                    </div>
                    <div
                      v-else-if="!item.like_status"
                      @click.stop="starClick(1, item)"
                    >
                      <img src="./images/xin.png" alt="" />
                    </div>
                    <span>{{ item.like_nums }}</span>
                  </div>
                </div>
              </div>
            </div>
          </template>

**Comment by blackomilk** [comment]
> 懒加载组件用的哪个？

<LazyImg
                  :url="url + item.img_url"
                  v-on:contextmenu="preventContextMenu"
                  ref="lazyImg"
                  @success="lazyImgLoadSuccess1"
                />

**Comment by blackomilk** [comment]
> 懒加载组件用的哪个？

懒加载图片我看有个padding-bottom，最大值是200吗

**Comment by heikaimu** [comment]
你左边那个红色的正方形图片，我看是铺满了的，你有检查过没铺满的卡片的模糊图和清晰图片是一个比例吗？

**Comment by heikaimu** [comment]
loadProps: {
  loading,
  error,
  ratioCalculator: (width, height) => {
    // 我设置了最小宽高比
    const minRatio = 3 / 4;
    const maxRatio = 4 / 3;
    // 获取当前图片的比例
    const curRatio = width / height;
    // 如果当前图片比列不在此范围内，我们取最小或者最大值
    if (curRatio < minRatio) {
      return minRatio;
    } else if (curRatio > maxRatio) {
      return maxRatio;
    } else {
      return curRatio;
    }
  }
}

**Comment by blackomilk** [comment]
> 你左边那个红色的正方形图片，我看是铺满了的，你有检查过没铺满的卡片的模糊图和清晰图片是一个比例吗？

<img width="307" alt="image" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/42260316/baa94393-4be5-4bfb-82c0-b0fc47a68fea">
这种图片宽高比是1:1，这种的没问题，就是那种竖图有问题，竖图宽高是1:2的。
就是不明白为啥底图能铺满，在上边盖一层，同样的图片为啥铺不满了呢。我就看到懒加载图片那个标签上有个padding-bottom,感觉是这个引起的

**Comment by heikaimu** [comment]
emmm....我知道原因了。这是一个数学问题。
100x100的时候，你给了一个20的边距。这时候你除开边距剩下80x80，他还是1:1
100x200的时候，你给了一个20，那么就变成80x180，当然不是1:2咯

**Comment by blackomilk** [comment]
> emmm....我知道原因了。这是一个数学问题。 100x100的时候，你给了一个20的边距。这时候你除开边距剩下80x80，他还是1:1 100x200的时候，你给了一个20，那么就变成80x180，当然不是1:2咯

没想到这。。。这种情况有啥好的处理办法吗，间距还必须保留

**Comment by heikaimu** [comment]
<style>
    .card {
      position: relative;
      
      &__bg {
        position: absolute;
        left: 0;
        top: 0;
        right: 0;
        bottom: 0;
        z-index: 1;
      }

      &__img {
        position: relative;
        z-index: 2;
        padding: 20rem;
      }
    }
  </style>

<div class="card">
  <div class="card__bg">
    <lazyImg/>
  </div>
  <div class="card__img">
    <lazyImg/>
  </div>
</div>

用这种结构试试，以清晰图正确比例为准，背景图比例无所谓的。

**Comment by heikaimu** [comment]
```
  <style>
    .card {
      position: relative;
      
      &__bg {
        position: absolute;
        left: 0;
        top: 0;
        right: 0;
        bottom: 0;
        z-index: 1;
      }

      &__img {
        position: relative;
        z-index: 2;
        padding: 20rem;
      }
    }
  </style>

<div class="card">
  <div class="card__bg">
    <lazyImg/>
  </div>
  <div class="card__img">
    <lazyImg/>
  </div>
</div>
```

这种结构试试。

**Comment by heikaimu** [comment]
其实，你这个没必要用2张图的。你的背景图就用的你主图然后给个高斯模糊的滤镜就行了。这样还能少加载一倍的资源。你在lazyImage加载成功的事件里面给你背景图赋地址就行了。

**Comment by blackomilk** [comment]
好的，我试试，感谢

**Comment by junqiang1992** [comment]
@blackomilk 你这个照片显示的样式可以提供下吗

**Comment by ChengChengCUG** [comment]
<LazyImg :url="item.coverImage"/>

为什么不显示图片呢？变量链接都是正常的啊，用下面的图片标签就可以正常显示图片，但是貌似没有懒加载属性
