### ISSUE TITLE
关于移动端兼容

### ISSUE THREAD

**Issue by EthanZhq** [heikaimu/vue3-waterfall-plugin#58]
![image](https://github.com/heikaimu/vue3-waterfall-plugin/assets/51309238/e0f22040-212f-4962-b42f-69fb0fad7956)
在使用时候 app端 似乎不兼容  该插件不兼容app端么

**Comment by heikaimu** [comment]
目前只支持PC和H5，没有考虑app的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue3-waterfall-plugin] 关于移动端兼容 (Issue #58)





 
image.png (view on web)
 在使用时候 app端 似乎不兼容  该插件不兼容app端么
