### ISSUE TITLE
强制更新列表不行

### ISSUE THREAD

**Issue by Purpledayer** [heikaimu/vue3-waterfall-plugin#59]
<Waterfall ref="waterfall"></Waterfall>

const waterfall = ref(null)
waterfall.value.renderer()

这个更新方法不管用呀，waterfall.value 下面没有renderer这个函数是怎么回事？

**Comment by heikaimu** [comment]
有这个方法，你咋个用的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue3-waterfall-plugin] 强制更新列表不行 (Issue #59)





 

 
const waterfall = ref(null)
 waterfall.value.renderer()
 
这个更新方法不管用呀，waterfall.value 下面没有renderer这个函数是怎么回事？

**Comment by Purpledayer** [comment]
<Waterfall ref="waterfall" 
                        :lazyload="true" 
                        :animation-effect="conf.options.animationEffect" 
                        :animation-duration="conf.options.animationDuration" 
                        :breakpoints="conf.options.breakpoints" 
                        :animation-delay="conf.options.animationDelay" 
                        :list="state.listData"
                        :column-gap="conf.options.columnGap"
                    >
                        <template #item="data">
                            <addCom v-if="data.item.type=='add'"></addCom>
                            <emptyNode v-else-if="data.item.sensor_list.length==0" :data="data.item"/>
                            <listCom v-else :data="data.item" @reenderFun="reenderFun"></listCom>
                        </template>
                    </Waterfall>
                    

const waterfall:any = ref(null);


const reenderFun=()=>{
    console.log( waterfall.value);
}
                    就这样呀，这样不行么

**Comment by heikaimu** [comment]
你现在调用&nbsp;renderer() 这个方法报错了？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heikaimu/vue3-waterfall-plugin] 强制更新列表不行 (Issue #59)





 

 <template #item="data"&gt;
 
 
 <listCom v-else :data="data.item" @reenderFun="reenderFun"&gt;
 
 
 
const waterfall:any = ref(null);
 
const reenderFun=()=&gt;{
 console.log( waterfall.value);
 }
 就这样呀，这样不行么

**Comment by Purpledayer** [comment]
是的 而且打印出来也没有这个方法
![1](https://github.com/heikaimu/vue3-waterfall-plugin/assets/10919054/7de19d5a-c520-4737-b42d-a31bf1803952)
![2](https://github.com/heikaimu/vue3-waterfall-plugin/assets/10919054/d1e0454f-f0d0-455a-884e-99a29d0aec95)

**Comment by heikaimu** [comment]
你试试在外面写一个按钮然后手动去触发这个函数看看。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heikaimu/vue3-waterfall-plugin] 强制更新列表不行 (Issue #59)





 
是的 而且打印出来也没有这个方法
 1.png (view on web)
 2.png (view on web)

**Comment by Purpledayer** [comment]
![image](https://github.com/heikaimu/vue3-waterfall-plugin/assets/10919054/644a7600-76db-443d-b78b-da3a9c68fef0)
外部的按钮手动触发结果还是一样的

**Comment by Purpledayer** [comment]
只有2.4.2版本有这个方法？？？？别的都没啊？？

**Comment by heikaimu** [comment]
你下载的哪个版本

**Comment by heikaimu** [comment]
我这边安装了一个最新的 2.4.3版本，也能成功的获取到这个方法。你这个我就有点儿搞不懂了。

**Comment by Purpledayer** [comment]
最开始的2.2.2与最新的2.4.3版本都不行，我安装了2.4.2才行

**Comment by heikaimu** [comment]
你估计有缓存哦。2.4.3是肯定可以的。

**Comment by Purpledayer** [comment]
我晚点再试试看2.4.3版本的

**Comment by zhlhuang** [comment]
> 我晚点再试试看2.4.3版本的

为什么我这边2.4.3也不行，打印有  renderer 方法
