### ISSUE TITLE
为什么控制台每张图片会出现两次相同的图片请求？

### ISSUE THREAD

**Issue by dsitn201703** [heikaimu/vue3-waterfall-plugin#66]
为什么控制台每张图片会出现两次相同的图片请求？当图片多了以后会占用带宽吧
<img width="960" alt="Snipaste_2024-07-01_15-42-08" src="https://github.com/heikaimu/vue3-waterfall-plugin/assets/26814281/c342d4d7-5c87-4cc7-abfc-0027828f0047">

**Comment by heikaimu** [comment]
图片地址一样的话第二次都是走的缓存，没啥问题。具体原因我后面有时间再看下。

**Comment by heikaimu** [comment]
这个问题修复了哈，v2.5.1版本
