### ISSUE TITLE
PC 端使用报错

### ISSUE THREAD

**Issue by Tricker39** [heikaimu/vue3-waterfall-plugin#7]
版本："vue-waterfall-plugin-next": "^2.1.7"
 Cannot read properties of null (reading 'isCE')

**Comment by Jcanno** [comment]
+1

**Comment by heikaimu** [comment]
需要提供环境，node版本号，浏览器类型方便测试

**Comment by LeifJG** [comment]
> 需要提供：环境、node版本、浏览器、依赖安装方式

https://segmentfault.com/a/1190000041416388?sort=votes
可以参考下这个，我这边安装下来也是一样会报这个错误

**Comment by heikaimu** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午5:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heikaimu/vue3-waterfall-plugin] PC 端使用报错 (Issue #7)





  
需要提供：环境、node版本、浏览器、依赖安装方式
  
https://segmentfault.com/a/1190000041416388?sort=votes
 可以参考下这个，我这边安装下来也是一样会报这个错误
