### ISSUE TITLE
上一行和下一行之间的空隙怎么调整啊？

### ISSUE THREAD

**Issue by jessicap** [heikaimu/vue3-waterfall-plugin#70]
每个waterfall-card的高度都多出一节空白的，上一行和下一行之间很空，不知道怎么调整

**Comment by heikaimu** [comment]
最好提供代码和截图，不然我也不知道你啥情况

**Comment by Dave-12138** [comment]
默认的间距已经挺小了，如果设置了`gutter`参数还觉得空隙大，考虑检查一下是不是自己`margin`写大了，插槽内容物根元素的上下`margin`会影响卡牌上下间距，虽然左右似乎不会。

**Comment by heikaimu** [comment]
你可以尝试把卡片内的布局用margin改成padding，大概率能解决。
