### ISSUE TITLE
list为什么必须传src呢

### ISSUE THREAD

**Issue by RoadsideParty** [heikaimu/vue3-waterfall-plugin#71]
![image](https://github.com/user-attachments/assets/963c0b7c-8557-45c4-883d-8af796b9f8af)

**Comment by heikaimu** [comment]
这是图片的瀑布流啊。所以传个图片地址应该的噻。

**Comment by RoadsideParty** [comment]
瀑布流不只有图片,ViewCard应该只保留必要属性,额外的属性交给使用者定义

**Comment by heikaimu** [comment]
嗯，有道理，改了下，2.5.3，就任意字段了。
