### ISSUE TITLE
貌似不能配置填满容器，某些情况下出现超出容器或小于容器

### ISSUE THREAD

**Issue by anzhiyu-c** [heikaimu/vue3-waterfall-plugin#75]
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/c6759b2f-89f6-426e-a21d-1dfdc83d40c0">
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/8ce67286-3860-4007-936a-02b2eb7de083">

**Comment by heikaimu** [comment]
你看下你是什么版本，如果不是最新的版本就更新下，左右没显示全的BUG在新版本修复了。

**Comment by heikaimu** [comment]
你如果希望他能全屏幕填满的显示，就用移动端的断点方式。把开始的分辨率设置大一点。比如：
```
    breakpoints: {
      type: Object,
      default: () => ({
        2000: {
          // when wrapper width < 2000
          rowPerView: 6,
        },
        800: {
          // when wrapper width < 800
          rowPerView: 2,
        },
        500: {
          // when wrapper width < 500
          rowPerView: 1,
        },
      }),
    },
```
自己多写一个断点，每个断点设置一个列数。

**Comment by anzhiyu-c** [comment]
更新到最新版本了，但是现在有个问题就是，我没有办法让他充满容器，两边总会留下很大的空白

**Comment by anzhiyu-c** [comment]
https://coding-pages-bucket-415964-8382475-13401-506140-1252701316.cos-website.ap-hongkong.myqcloud.com/#/

可以参考一下这个的实现

**Comment by anzhiyu-c** [comment]
> 你如果希望他能全屏幕填满的显示，就用移动端的断点方式。把开始的分辨率设置大一点。比如：
> 
> ```
>     breakpoints: {
>       type: Object,
>       default: () => ({
>         2000: {
>           // when wrapper width < 2000
>           rowPerView: 6,
>         },
>         800: {
>           // when wrapper width < 800
>           rowPerView: 2,
>         },
>         500: {
>           // when wrapper width < 500
>           rowPerView: 1,
>         },
>       }),
>     },
> ```
> 
> 自己多写一个断点，每个断点设置一个列数。

这种方法，其实不太行，因为宽度始终被固定了，某些情况还是无法覆盖到，没发做到《完美适配》😭

**Comment by heikaimu** [comment]
不会啊，用断点的时候，宽度是失效的，卡片宽度会根据你的列数和屏幕宽度自动计算。你试试就知道了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月30日(星期五) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [heikaimu/vue3-waterfall-plugin] 貌似不能配置填满容器，某些情况下出现超出容器或小于容器 (Issue #75)














  
你如果希望他能全屏幕填满的显示，就用移动端的断点方式。把开始的分辨率设置大一点。比如：
     breakpoints: {       type: Object,       default: () =&gt; ({         2000: {           // when wrapper width < 2000           rowPerView: 6,         },         800: {           // when wrapper width < 800           rowPerView: 2,         },         500: {           // when wrapper width < 500           rowPerView: 1,         },       }),     },  
自己多写一个断点，每个断点设置一个列数。
  
这种方法，其实不太行，因为宽度始终被固定了，某些情况还是无法覆盖到，没发做到《完美适配》😭

**Comment by anzhiyu-c** [comment]
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/98cf150b-5811-4ec7-be1e-4776b71b4a31">
<img width="1698" alt="image" src="https://github.com/user-attachments/assets/9e4a2059-e62b-437b-98a6-a3f26c438f29">
<img width="465" alt="image" src="https://github.com/user-attachments/assets/019c0bc4-6df8-4855-a1b6-4c47e1d68040">
<img width="730" alt="image" src="https://github.com/user-attachments/assets/2cd83201-4236-46df-8500-1ee97ce155d8">

**Comment by heikaimu** [comment]
我在example里面写了一个铺满的列子，你看下，然后检查下代码。

**Comment by heikaimu** [comment]
目前最新的版本是 2.6.0 ,你检查下是否正确。
