### ISSUE TITLE
重新排列的时候会发生重叠的现象

### ISSUE THREAD

**Issue by kurodasense** [heikaimu/vue3-waterfall-plugin#79]
![image](https://github.com/user-attachments/assets/db48b822-0840-4c8a-b64b-3ae1ac774e32)
如图

**Comment by kurodasense** [comment]
我的代码是这样的，不知道是不是key设置错误呢
`<Waterfall v-else :list="sortedAnimeDates" :width="500" rowKey="item.date_id">
      <template #default="{ item }">
        <card-item :date="item" :key="item.date_id" />
      </template>
    </Waterfall>`

**Comment by heikaimu** [comment]
试试把你的文字容器高度固定死
