### ISSUE TITLE
图片加载慢的时候会导致叠层问题出现

### ISSUE THREAD

**Issue by poggioxk** [heikaimu/vue3-waterfall-plugin#82]

**Comment by heikaimu** [comment]
top都是根据图片加载之后的高度计算出来的。你可以预先给外容器写一个最小高。

**Comment by poggioxk** [comment]
有没有一种办法可以手动去触发重新排版，这样我可以自己在需要的时间去触发重新排版

**Comment by poggioxk** [comment]
![4bf7622019fcee601b19a2d8e69a4dc](https://github.com/user-attachments/assets/f548ce6b-155e-4ef5-9da3-7132e52adae1)
这是我的图片

**Comment by heikaimu** [comment]
你说的叠加是指的哪个位置？
