### ISSUE TITLE
跳转新路由在回来就重新绘制列表了，并且滚动高度还改变到最顶部了

### ISSUE THREAD

**Issue by jianfei889** [heikaimu/vue3-waterfall-plugin#84]
https://github.com/user-attachments/assets/7810638f-5ded-4aa4-854c-fcadc326d192

想知道这里列表，我点击详情跳转进入新的页面之后再返回，它怎么就重新绘制列表了，我这里是没有做api接口列表的变更的，数据也没变的。或者我可以怎么改好这个问题吗

**Comment by heikaimu** [comment]
你销毁组件了，他是会重新渲染的

**Comment by jianfei889** [comment]
> 你销毁组件了，他是会重新渲染的

没有销毁的。看了一遍源码，是每次回来时貌似触发了宽度还是那个元素的更新改变，然后就renden重新渲染了。不过现在还是有一个问题。
  问题：现在重渲染的问题好了，但是进入新路由再回来页面时（已经做了keep-alive缓存了，可以保证页面组件不被销毁，数据也不会改变）,滚动的高度没有回到上一个，它又回到最顶部了

**Comment by heikaimu** [comment]
滚动的高度这个其实简单，你自己在外面写就行了，每次离开当前页面的时候记录一下滚动的距离，回来的时候判断有没有季录值，有就滚动回去就行了。

**Comment by heikaimu** [comment]
```
const scrollableDiv = document.getElementById('scrollableDiv');
const SCROLL_KEY = 'scrollableDivScrollTop'; // 存储滚动位置的键名

// 恢复滚动位置
window.addEventListener('load', () => {
  const savedScrollTop = sessionStorage.getItem(SCROLL_KEY);
  if (savedScrollTop) {
    scrollableDiv.scrollTop = parseInt(savedScrollTop, 10);
  }
});

// 记录滚动位置
scrollableDiv.addEventListener('scroll', () => {
  sessionStorage.setItem(SCROLL_KEY, scrollableDiv.scrollTop);
});

```
大概就这个意思

**Comment by jianfei889** [comment]
> ```
> const scrollableDiv = document.getElementById('scrollableDiv');
> const SCROLL_KEY = 'scrollableDivScrollTop'; // 存储滚动位置的键名
> 
> // 恢复滚动位置
> window.addEventListener('load', () => {
>   const savedScrollTop = sessionStorage.getItem(SCROLL_KEY);
>   if (savedScrollTop) {
>     scrollableDiv.scrollTop = parseInt(savedScrollTop, 10);
>   }
> });
> 
> // 记录滚动位置
> scrollableDiv.addEventListener('scroll', () => {
>   sessionStorage.setItem(SCROLL_KEY, scrollableDiv.scrollTop);
> });
> ```
> 
> 大概就这个意思

好的，谢谢回复，我先调试一遍看看
