### ISSUE TITLE
Waterfall load-props 属性中未定义 error （错误图片）时，LazyImg @error 无法触发

### ISSUE THREAD

**Issue by nicet** [heikaimu/vue3-waterfall-plugin#85]
**预期行为：**
在 LazyImg url返回错误（404，500等）时，error事件被抛出。

**实际行为：**
error事件未抛出，控制台 Uncaught (in promise) Error: Image failed to load!And failed src was: ...

**问题定位：**
https://github.com/heikaimu/vue3-waterfall-plugin/blob/ea5e662690f18868d8d8804091cc511e0080084a/lib/utils/Lazy.ts#L117-L128

```javascript
      .catch(() => {
        const imgItem = this._realObserver(el)
        imgItem && imgItem.disconnect()
        if (error) {  /// error === "", falsy value，跳过if执行
          el.setAttribute('lazy', LifecycleEnum.ERROR)
          el.setAttribute('src', error)
          callback(false) // 未调用callback
        }
        this._log(() => {
          throw new Error(`Image failed to load!And failed src was: ${src} `) // 实际执行
        })
      })
```

**Comment by heikaimu** [comment]
![Uploading WeChat942b20941c12069a24fc7498a4cfcafe.jpg…]()
有抛出啊

**Comment by heikaimu** [comment]
![WeChat942b20941c12069a24fc7498a4cfcafe](https://github.com/user-attachments/assets/3e53df09-c2b7-4327-ae4e-6d33532621dc)
有抛出啊

**Comment by nicet** [comment]
不是指 异常未被抛出，而是 LazyImg 的 error 事件未被抛出。

此prop为默认值时
https://github.com/heikaimu/vue3-waterfall-plugin/blob/ea5e662690f18868d8d8804091cc511e0080084a/lib/utils/Lazy.ts#L25

LazyImg的error事件不再被 emit
https://github.com/heikaimu/vue3-waterfall-plugin/blob/ea5e662690f18868d8d8804091cc511e0080084a/lib/components/LazyImg.vue#L63


如果这是预期行为，可以关闭issue

**Comment by heikaimu** [comment]
你应该调用错方法了，这样调用，我这边测试了可以
![WeChat5a53a8eb11708c1340ad30014b225130](https://github.com/user-attachments/assets/74f8a134-fc7d-4cd3-83c9-cdbd0719aff3)

**Comment by heikaimu** [comment]
![5b7ffb24-c2b5-4dfd-90db-eae90860f8bc](https://github.com/user-attachments/assets/e9629ae1-7ac7-4f84-9ba8-e01f602dc7e6)

**Comment by nicet** [comment]
已解决
