### ISSUE TITLE
懒加载图片请求两次

### ISSUE THREAD

**Issue by guoguo1991** [heikaimu/vue3-waterfall-plugin#86]
瀑布流 封面图跟头像 使用懒加载LazyImg组件，滑动加载过程中，头像跟封面图均会发起两次请求。请问如何解决
版本：2.5.1，2.5.7 以及最新的2.6.4均如此

**Comment by heikaimu** [comment]
第二次是缓存吧，第一次是我要去请求图片然后拿它的宽高，第二次是img src渲染的时候发起的，逻辑就是这样的。第二次是直接拿的第一次的缓存，没问题的。

**Comment by guoguo1991** [comment]
好的。图片的宽高是已知的 请问有办法可以去掉第一次请求么

**Comment by heikaimu** [comment]
目前没有办法

**Comment by guoguo1991** [comment]
好的 感谢♥️
