### ISSUE TITLE
如何去除动画

### ISSUE THREAD

**Issue by Jcanno** [heikaimu/vue3-waterfall-plugin#9]

**Comment by heikaimu** [comment]
动画名配置的时候随便乱写一个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月3日(星期一) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue3-waterfall-plugin] 如何去除动画 (Issue #9)
